import java.util.Random;
import java.util.Scanner;
public class JurassicParkGame {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        Random rand = new Random();
        Hero Alan = new Hero("Alan", 100);
        Villain Henry = new Villain("Henry", 100);

        System.out.println("Welcome to the Jurrassic Park Game!");
        System.out.println("This is a two player game. A random number will be generated by the system. Both players will choose a random number. Whoever is the farthest will take damage of 20. Game will continue until one of the players die.");
        System.out.println("Alan faces his eternal enemy Henry");
        System.out.println("Alan says 'I will not rest until you are dead Henry!!!'");
        System.out.println("Henry says 'I will not spare you either!'");
        System.out.println("Both say at the same time 'Let's see who stays alive till the end'");
        System.out.println("Choose your character player 1: (1) Hero Alan or (2) Villain Henry");
        int choice = sc.nextInt();

        if (choice == 1) {
            System.out.println("Player 1 chooses Alan");
            System.out.println("Player 2 is Henry");
           // Alan.activateMachineGun();
        } else if (choice == 2) {
            System.out.println("Player 1 chooses Henry");
            System.out.println("Player 2 is Alan");
           // Henry.activateMachineGun();
        } else {
            System.out.println("Invalid choice.");
        }
        
        while (Alan.getHealth() > 0 && Henry.getHealth() > 0) {
            int sysgenint = rand.nextInt(100);
            System.out.println("Player 1 choose a random number between 1 and 100");
            int player1choice = sc.nextInt();
            System.out.println("Player 2 choose a random number between 1 and 100");
            int player2choice = sc.nextInt();
            System.out.println("The system generates the random numeber " + sysgenint);
            if (Math.abs(sysgenint - player1choice) < Math.abs(sysgenint - player2choice)){
                if(choice==1){
                    Henry.takeDamage(20);
                }
                else{
                    Alan.takeDamage(20);
                }
            }
            else if (Math.abs(sysgenint - player1choice)  > Math.abs(sysgenint - player2choice)){
                if(choice==1){
                    Alan.takeDamage(20);
                }
                else{
                    Henry.takeDamage(20);
                }
            }
            else{
                System.out.println("Both choosed the same number, both take equal damage!");
                Alan.takeDamage(20);
                Henry.takeDamage(20);
            }
        }
           

        // Game over
        if (Alan.getHealth() <= 0 && Henry.getHealth() <= 0){
            System.out.println("It's a draw, Both Hero and Villain die at the same time!");
        }
        else if (Alan.getHealth() <= 0) {
            System.out.println("Henry wins!");
            System.out.println("Have you seen who is the boss.");
        } 
        else{
            System.out.println("Alan wins!");
            System.out.println("Have you seen who is the boss.");
        
        }

        sc.close();

    }
    

}

